[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node ace migration:run --force && node build/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
